export enum SettingsName {
    LETTER_ANIMATION_DURATION_IN_MS = 'LETTER_ANIMATION_DURATION_IN_MS',
    NUMBER_OF_WORD_LOADED_AT_ONCE = 'NUMBER_OF_WORD_LOADED_AT_ONCE',
    NUMBER_OF_TRIES = 'NUMBER_OF_TRIES',
    DELAY_BEFORE_NEW_GAME_IN_MS = 'DELAY_BEFORE_NEW_GAME_IN_MS',
    GAME_LANGUAGE = 'GAME_LANGUAGE'
}