name: Build and Deploy Docker Image on Release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
      - name: Extract the release tag name
        run: echo "RELEASE_TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      - name: Build the Docker image with both tags
        run: >
          docker build . 
          --tag naofeleal/motus_ihm:${{ env.RELEASE_TAG_NAME }}
          --tag naofeleal/motus_ihm:latest
      
      - name: Push both tags of the Docker image
        run: docker push --all-tags naofeleal/motus_ihm
